### ISSUE TITLE
<paper-button> onclick only fired on second click

### ISSUE THREAD

**Issue by 7Ds7** [PolymerElements/paper-behaviors#34]
After the latest update a regular paper button in any browser which is not Chrome only fire click events upon a second click
```
<paper-button raised onclick="console.log('trigger');">click me</paper-button>
```

Notice that the console.log only shows when you click a second time.

If the paper ripple behaviour is removed from here https://github.com/PolymerElements/paper-behaviors/blob/master/paper-button-behavior.html#L94 and if we use a button without the ripple effect, then it works as expected.

Probably the problem is a bit further (state behaviours) although i could not figure it out where exactly it goes wrong

**Comment by 7Ds7** [comment]
Here is a codepen demonstrating the case, notice that in FF/Safari, or any other browser that relies on webcomponents.js polyfills the click action attached to the paper-button element is only triggered after the second click
http://codepen.io/anon/pen/NGvyPB

**Comment by notwaldorf** [comment]
Heads up: there's a lot of duplicated issues around this, so I'm going to merge all of them into one, this one, since it's very likely a behaviour issue (around ripple) and not an individual item issue.

**Comment by notwaldorf** [comment]
TL: DR for posterity:
In one of the issues referenced, @azakus made a nice non-ripple jsbin(http://jsbin.com/licufenisi/edit?html,css,console,output) that points to the problem being creating a node with `position:absolute` while in the middle of dealing with a mouse event. This is relevant here because we're creating the `paper-ripple` in the middle of a down event, and it has `position:absolute`.

Then @cdata figured out that adding `pointer-events:none` in the `focus:after` selector fixes the problem, so I think the same needs to be done when we're creating the ripple. On it!

**Comment by 7Ds7** [comment]
Thanks a lot for the heads up. 
I also noticed that playing around with the pointer-events inside the paper-button element, made the behaviour change. 
But thanks to your input and @cdata findings i figured that changing the the paper-ripple element to ```pointer-events: none;``` works as some kind of hot fix.

http://codepen.io/anon/pen/epEVad

**Comment by gstroup** [comment]
@notwaldorf 
I don't think this issue is fixed. I just pulled down paper-elements 1.0.5, but I still see the same buggy behavior in Firefox. When I apply the style "pointer-events: none" in my application as suggested by @kritollm, then the problem is fixed. Can we reopen this one?

**Comment by notwaldorf** [comment]
paper-elements `1.0.5` is from August, which is a bit suspicious (the latest release is `1.0.6`). In any case, here is a jsbin that's using the latest version of `paper-button` and its dependencies, and it works fine in FF: http://jsbin.com/dejemi/edit?html,output
